# Generated by Django 2.0.5 on 2018-05-10 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OnlineDocument', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='original_file',
            field=models.FileField(upload_to='static/document/original/%Y/%M', verbose_name='原始文件地址'),
        ),
        migrations.AlterField(
            model_name='document',
            name='pdf_file',
            field=models.FileField(default='static/document/pdf/default.pdf', upload_to='static/document/pdf/%Y/%M', verbose_name='PDF'),
        ),
    ]
