# Generated by Django 2.0.5 on 2018-05-14 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OnlineDocument', '0002_auto_20180510_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='tags',
            field=models.ManyToManyField(blank=True, to='OnlineDocument.Tag'),
        ),
    ]
