# Generated by Django 2.0.5 on 2018-05-23 16:59

from django.db import migrations, models
import util.storage


class Migration(migrations.Migration):

    dependencies = [
        ('OnlineDocument', '0004_auto_20180514_2326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='original_file',
            field=models.FileField(storage=util.storage.DocumentStorage(), upload_to='static/document/original/%Y/%M', verbose_name='原始文件地址'),
        ),
    ]
